from dotenv import load_dotenv
import os
from pymongo import MongoClient

load_dotenv()
client = MongoClient(os.getenv("MONGO_URI"))
db = client["toursafe"]

new_destinations = [
    {"name": "Khajuraho", "ratings": {"avg": 4.5, "count": 1700}, "reviews": [{"user": "Anjali M", "text": "Incredible temple carvings", "rating": 5, "date": "2025-02-08"}], "attractions": ["Western Group of Temples", "Khajuraho Dance Festival", "Raneh Falls"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 23, "condition": "Pleasant"}, "location": {"lat": 24.8318, "lng": 79.9199}, "entry_fee": 40, "events": [{"name": "Khajuraho Dance Festival", "start_date": "2026-02-20", "end_date": "2026-02-26"}], "avg_cost": 2600},
    {"name": "Bhopal", "ratings": {"avg": 4.2, "count": 1400}, "reviews": [{"user": "Sanjay P", "text": "City of lakes, underrated gem", "rating": 4, "date": "2025-03-14"}], "attractions": ["Upper Lake", "Van Vihar National Park", "Bhimbetka Caves"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 24, "condition": "Pleasant"}, "location": {"lat": 23.2599, "lng": 77.4126}, "entry_fee": 0, "events": [], "avg_cost": 2100},

    {"name": "Rann of Kutch", "ratings": {"avg": 4.6, "count": 2000}, "reviews": [{"user": "Hetal J", "text": "White desert under full moon is magical", "rating": 5, "date": "2025-12-05"}], "attractions": ["White Rann", "Kalo Dungar", "Kutch Museum"], "season": {"best_months": [11, 12, 1, 2]}, "weather": {"avg_temp": 20, "condition": "Dry"}, "location": {"lat": 23.7337, "lng": 69.8597}, "entry_fee": 100, "events": [{"name": "Rann Utsav", "start_date": "2025-11-20", "end_date": "2026-02-20"}], "avg_cost": 3200},
    {"name": "Somnath", "ratings": {"avg": 4.5, "count": 1900}, "reviews": [{"user": "Mehul D", "text": "Powerful temple by the sea", "rating": 5, "date": "2025-01-18"}], "attractions": ["Somnath Temple", "Triveni Sangam", "Bhalka Tirth"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 26, "condition": "Warm"}, "location": {"lat": 20.8880, "lng": 70.4012}, "entry_fee": 0, "events": [], "avg_cost": 2000},

    {"name": "Puri", "ratings": {"avg": 4.5, "count": 2600}, "reviews": [{"user": "Subrat N", "text": "Jagannath Temple and beach combo", "rating": 5, "date": "2025-06-20"}], "attractions": ["Jagannath Temple", "Puri Beach", "Konark Sun Temple"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 27, "condition": "Warm"}, "location": {"lat": 19.8135, "lng": 85.8312}, "entry_fee": 0, "events": [{"name": "Rath Yatra", "start_date": "2026-06-15", "end_date": "2026-06-17"}], "avg_cost": 2400},
    {"name": "Konark", "ratings": {"avg": 4.6, "count": 1500}, "reviews": [{"user": "Priyanka S", "text": "Sun Temple architecture is unmatched", "rating": 5, "date": "2025-01-22"}], "attractions": ["Konark Sun Temple", "Chandrabhaga Beach", "Konark Museum"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 26, "condition": "Warm"}, "location": {"lat": 19.8876, "lng": 86.0945}, "entry_fee": 40, "events": [{"name": "Konark Dance Festival", "start_date": "2025-12-01", "end_date": "2025-12-05"}], "avg_cost": 2200},

    {"name": "Tirupati", "ratings": {"avg": 4.6, "count": 4800}, "reviews": [{"user": "Lakshmi R", "text": "Deeply spiritual experience", "rating": 5, "date": "2025-02-01"}], "attractions": ["Tirumala Venkateswara Temple", "Silathoranam", "ISKCON Temple"], "season": {"best_months": [9, 10, 11, 12, 1, 2]}, "weather": {"avg_temp": 25, "condition": "Warm"}, "location": {"lat": 13.6288, "lng": 79.4192}, "entry_fee": 0, "events": [], "avg_cost": 1800},
    {"name": "Araku Valley", "ratings": {"avg": 4.4, "count": 1100}, "reviews": [{"user": "Ravi Teja", "text": "Coffee plantations and tribal culture", "rating": 4, "date": "2025-03-25"}], "attractions": ["Borra Caves", "Coffee Museum", "Tribal Museum"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 22, "condition": "Pleasant"}, "location": {"lat": 18.3273, "lng": 82.8747}, "entry_fee": 40, "events": [], "avg_cost": 2000},

    {"name": "Hyderabad", "ratings": {"avg": 4.4, "count": 5600}, "reviews": [{"user": "Fahim K", "text": "Charminar and biryani culture", "rating": 4, "date": "2025-04-10"}], "attractions": ["Charminar", "Golconda Fort", "Ramoji Film City"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 27, "condition": "Warm"}, "location": {"lat": 17.3850, "lng": 78.4867}, "entry_fee": 0, "events": [], "avg_cost": 2800},

    {"name": "Gangtok", "ratings": {"avg": 4.6, "count": 2300}, "reviews": [{"user": "Pema S", "text": "Mountain views and monasteries", "rating": 5, "date": "2025-05-08"}], "attractions": ["Tsomgo Lake", "Nathula Pass", "Rumtek Monastery"], "season": {"best_months": [3, 4, 5, 10, 11]}, "weather": {"avg_temp": 15, "condition": "Cool"}, "location": {"lat": 27.3389, "lng": 88.6065}, "entry_fee": 0, "events": [], "avg_cost": 3400},

    {"name": "Srinagar", "ratings": {"avg": 4.7, "count": 3100}, "reviews": [{"user": "Bilal A", "text": "Paradise on earth, Dal Lake shikara ride", "rating": 5, "date": "2025-06-12"}], "attractions": ["Dal Lake", "Mughal Gardens", "Shankaracharya Temple"], "season": {"best_months": [4, 5, 6, 9, 10]}, "weather": {"avg_temp": 18, "condition": "Pleasant"}, "location": {"lat": 34.0837, "lng": 74.7973}, "entry_fee": 0, "events": [], "avg_cost": 3800},
    {"name": "Gulmarg", "ratings": {"avg": 4.6, "count": 1800}, "reviews": [{"user": "Ayesha M", "text": "Snow skiing and gondola rides", "rating": 5, "date": "2025-01-15"}], "attractions": ["Gulmarg Gondola", "Ski Slopes", "Alpather Lake"], "season": {"best_months": [12, 1, 2, 3, 4, 5]}, "weather": {"avg_temp": 5, "condition": "Snowy"}, "location": {"lat": 34.0484, "lng": 74.3805}, "entry_fee": 0, "events": [], "avg_cost": 4200},

    {"name": "Lonavala", "ratings": {"avg": 4.3, "count": 3400}, "reviews": [{"user": "Nikhil J", "text": "Weekend getaway from Mumbai/Pune", "rating": 4, "date": "2025-07-15"}], "attractions": ["Tiger Point", "Bhushi Dam", "Karla Caves"], "season": {"best_months": [7, 8, 9, 10, 11]}, "weather": {"avg_temp": 24, "condition": "Misty"}, "location": {"lat": 18.7546, "lng": 73.4062}, "entry_fee": 0, "events": [], "avg_cost": 2100},
    {"name": "Mahabaleshwar", "ratings": {"avg": 4.4, "count": 2500}, "reviews": [{"user": "Snehal K", "text": "Strawberry farms and viewpoints", "rating": 4, "date": "2025-08-02"}], "attractions": ["Elephant's Head Point", "Mapro Garden", "Venna Lake"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 20, "condition": "Cool"}, "location": {"lat": 17.9307, "lng": 73.6477}, "entry_fee": 0, "events": [], "avg_cost": 2500},
    {"name": "Ajanta Ellora", "ratings": {"avg": 4.7, "count": 2000}, "reviews": [{"user": "Omkar P", "text": "Ancient cave art is astonishing", "rating": 5, "date": "2025-02-25"}], "attractions": ["Ajanta Caves", "Ellora Caves", "Kailasa Temple"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 25, "condition": "Warm"}, "location": {"lat": 20.5519, "lng": 75.7033}, "entry_fee": 600, "events": [], "avg_cost": 2300},

    {"name": "Kaziranga", "ratings": {"avg": 4.6, "count": 1400}, "reviews": [{"user": "Bikash D", "text": "One-horned rhino safari was incredible", "rating": 5, "date": "2025-03-05"}], "attractions": ["Kaziranga National Park", "Rhino Safari", "Kakochang Waterfall"], "season": {"best_months": [11, 12, 1, 2, 3, 4]}, "weather": {"avg_temp": 24, "condition": "Pleasant"}, "location": {"lat": 26.5775, "lng": 93.1714}, "entry_fee": 650, "events": [], "avg_cost": 3600},

    {"name": "Bodh Gaya", "ratings": {"avg": 4.6, "count": 1600}, "reviews": [{"user": "Amitabh K", "text": "Deeply peaceful, where Buddha attained enlightenment", "rating": 5, "date": "2025-01-28"}], "attractions": ["Mahabodhi Temple", "Bodhi Tree", "Great Buddha Statue"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 21, "condition": "Pleasant"}, "location": {"lat": 24.6961, "lng": 84.9911}, "entry_fee": 0, "events": [], "avg_cost": 1900},

    {"name": "Kolkata", "ratings": {"avg": 4.3, "count": 6100}, "reviews": [{"user": "Souvik B", "text": "City of joy, amazing street food", "rating": 4, "date": "2025-05-30"}], "attractions": ["Victoria Memorial", "Howrah Bridge", "Dakshineswar Temple"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 26, "condition": "Humid"}, "location": {"lat": 22.5726, "lng": 88.3639}, "entry_fee": 0, "events": [{"name": "Durga Puja", "start_date": "2025-10-19", "end_date": "2025-10-23"}], "avg_cost": 2600},
    {"name": "Sundarbans", "ratings": {"avg": 4.4, "count": 900}, "reviews": [{"user": "Ritu M", "text": "Mangrove forest boat safari, spotted a tiger track", "rating": 5, "date": "2025-04-08"}], "attractions": ["Sundarbans National Park", "Sajnekhali Wildlife Sanctuary", "Boat Safaris"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 25, "condition": "Humid"}, "location": {"lat": 21.9497, "lng": 88.9468}, "entry_fee": 500, "events": [], "avg_cost": 4000},

    {"name": "Kausani", "ratings": {"avg": 4.4, "count": 700}, "reviews": [{"user": "Deepak S", "text": "Best Himalayan panorama in Uttarakhand", "rating": 5, "date": "2025-05-15"}], "attractions": ["Anasakti Ashram", "Rudradhari Falls", "Baijnath Temple"], "season": {"best_months": [3, 4, 5, 9, 10, 11]}, "weather": {"avg_temp": 16, "condition": "Cool"}, "location": {"lat": 29.8419, "lng": 79.6083}, "entry_fee": 0, "events": [], "avg_cost": 2000},

    {"name": "Chandigarh", "ratings": {"avg": 4.2, "count": 2100}, "reviews": [{"user": "Simran K", "text": "Well-planned city, Rock Garden is unique", "rating": 4, "date": "2025-06-18"}], "attractions": ["Rock Garden", "Sukhna Lake", "Rose Garden"], "season": {"best_months": [10, 11, 12, 2, 3]}, "weather": {"avg_temp": 22, "condition": "Pleasant"}, "location": {"lat": 30.7333, "lng": 76.7794}, "entry_fee": 0, "events": [], "avg_cost": 2400},

    {"name": "Diu", "ratings": {"avg": 4.3, "count": 1000}, "reviews": [{"user": "Rushi V", "text": "Quiet beaches, Portuguese heritage", "rating": 4, "date": "2025-04-22"}], "attractions": ["Diu Fort", "Nagoa Beach", "St. Paul's Church"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 27, "condition": "Warm"}, "location": {"lat": 20.7144, "lng": 70.9874}, "entry_fee": 0, "events": [], "avg_cost": 2200}
]

result = db.destinations.insert_many(new_destinations)
print(f"Inserted {len(result.inserted_ids)} new destinations")
print(f"Total destinations now: {db.destinations.count_documents({})}")
