from dotenv import load_dotenv
import os
from pymongo import MongoClient

load_dotenv()
client = MongoClient(os.getenv("MONGO_URI"))
db = client["toursafe"]

db.destinations.delete_many({})

destinations = [
    {"name": "Coorg", "ratings": {"avg": 4.5, "count": 1200}, "reviews": [{"user": "Ravi K", "text": "Beautiful coffee estates", "rating": 5, "date": "2025-03-10"}], "attractions": ["Abbey Falls", "Raja Seat", "Dubare Elephant Camp"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 22, "condition": "Pleasant"}, "location": {"lat": 12.3375, "lng": 75.8069}, "entry_fee": 50, "events": [{"name": "Kaveri Festival", "start_date": "2025-11-15", "end_date": "2025-11-17"}], "avg_cost": 2500},
    {"name": "Hampi", "ratings": {"avg": 4.7, "count": 2100}, "reviews": [{"user": "Sneha M", "text": "Incredible ruins, very peaceful", "rating": 5, "date": "2025-01-20"}], "attractions": ["Virupaksha Temple", "Vittala Temple", "Matanga Hill"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 28, "condition": "Warm and dry"}, "location": {"lat": 15.335, "lng": 76.46}, "entry_fee": 40, "events": [{"name": "Hampi Utsav", "start_date": "2025-11-03", "end_date": "2025-11-05"}], "avg_cost": 1800},
    {"name": "Chikmagalur", "ratings": {"avg": 4.6, "count": 980}, "reviews": [{"user": "Arjun P", "text": "Great trekking trails", "rating": 5, "date": "2025-02-14"}], "attractions": ["Mullayanagiri", "Baba Budangiri", "Hebbe Falls"], "season": {"best_months": [9, 10, 11, 12, 1, 2]}, "weather": {"avg_temp": 20, "condition": "Cool"}, "location": {"lat": 13.3161, "lng": 75.7720}, "entry_fee": 30, "events": [], "avg_cost": 2200},
    {"name": "Gokarna", "ratings": {"avg": 4.4, "count": 1500}, "reviews": [{"user": "Meera S", "text": "Quiet beaches, less crowded", "rating": 4, "date": "2025-04-05"}], "attractions": ["Om Beach", "Kudle Beach", "Mahabaleshwar Temple"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 27, "condition": "Warm"}, "location": {"lat": 14.5479, "lng": 74.3188}, "entry_fee": 0, "events": [], "avg_cost": 1500},
    {"name": "Mysuru", "ratings": {"avg": 4.6, "count": 3200}, "reviews": [{"user": "Kiran T", "text": "Palace is stunning at night", "rating": 5, "date": "2025-01-08"}], "attractions": ["Mysore Palace", "Chamundi Hills", "Brindavan Gardens"], "season": {"best_months": [9, 10, 11, 12, 1, 2]}, "weather": {"avg_temp": 26, "condition": "Pleasant"}, "location": {"lat": 12.2958, "lng": 76.6394}, "entry_fee": 70, "events": [{"name": "Mysuru Dasara", "start_date": "2025-10-01", "end_date": "2025-10-12"}], "avg_cost": 2000},
    {"name": "Ooty", "ratings": {"avg": 4.3, "count": 2700}, "reviews": [{"user": "Divya R", "text": "Cool weather year round", "rating": 4, "date": "2025-05-12"}], "attractions": ["Botanical Garden", "Ooty Lake", "Doddabetta Peak"], "season": {"best_months": [3, 4, 5, 9, 10]}, "weather": {"avg_temp": 15, "condition": "Cold"}, "location": {"lat": 11.4064, "lng": 76.6932}, "entry_fee": 30, "events": [], "avg_cost": 2800},
    {"name": "Wayanad", "ratings": {"avg": 4.5, "count": 1600}, "reviews": [{"user": "Anil V", "text": "Untouched forests, great for nature lovers", "rating": 5, "date": "2025-03-22"}], "attractions": ["Edakkal Caves", "Chembra Peak", "Banasura Sagar Dam"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 23, "condition": "Pleasant"}, "location": {"lat": 11.6854, "lng": 76.1320}, "entry_fee": 40, "events": [], "avg_cost": 2400},
    {"name": "Pondicherry", "ratings": {"avg": 4.4, "count": 1900}, "reviews": [{"user": "Nisha K", "text": "French quarter has amazing cafes", "rating": 4, "date": "2025-06-01"}], "attractions": ["Promenade Beach", "French Quarter", "Auroville"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 29, "condition": "Warm"}, "location": {"lat": 11.9416, "lng": 79.8083}, "entry_fee": 0, "events": [], "avg_cost": 2600},
    {"name": "Munnar", "ratings": {"avg": 4.7, "count": 2500}, "reviews": [{"user": "Rahul B", "text": "Tea gardens are breathtaking", "rating": 5, "date": "2025-02-28"}], "attractions": ["Tea Museum", "Eravikulam National Park", "Mattupetty Dam"], "season": {"best_months": [9, 10, 11, 12, 1, 2]}, "weather": {"avg_temp": 18, "condition": "Cool"}, "location": {"lat": 10.0889, "lng": 77.0595}, "entry_fee": 50, "events": [], "avg_cost": 3000},
    {"name": "Bandipur", "ratings": {"avg": 4.2, "count": 900}, "reviews": [{"user": "Sunil G", "text": "Great safari experience", "rating": 4, "date": "2025-04-18"}], "attractions": ["Bandipur National Park", "Safari Zones", "Himavad Gopalaswamy Betta"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 25, "condition": "Warm"}, "location": {"lat": 11.6717, "lng": 76.6280}, "entry_fee": 300, "events": [], "avg_cost": 2100},

    {"name": "Jaipur", "ratings": {"avg": 4.6, "count": 5200}, "reviews": [{"user": "Aditya S", "text": "The Pink City is stunning", "rating": 5, "date": "2025-01-15"}], "attractions": ["Hawa Mahal", "Amber Fort", "City Palace"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 24, "condition": "Dry and warm"}, "location": {"lat": 26.9124, "lng": 75.7873}, "entry_fee": 200, "events": [{"name": "Jaipur Literature Festival", "start_date": "2026-01-20", "end_date": "2026-01-24"}], "avg_cost": 3200},
    {"name": "Udaipur", "ratings": {"avg": 4.7, "count": 4100}, "reviews": [{"user": "Priya D", "text": "City of lakes is magical", "rating": 5, "date": "2025-02-10"}], "attractions": ["Lake Pichola", "City Palace Udaipur", "Jag Mandir"], "season": {"best_months": [9, 10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 25, "condition": "Pleasant"}, "location": {"lat": 24.5854, "lng": 73.7125}, "entry_fee": 300, "events": [], "avg_cost": 3500},
    {"name": "Jaisalmer", "ratings": {"avg": 4.5, "count": 2800}, "reviews": [{"user": "Vikram J", "text": "Desert safari was unforgettable", "rating": 5, "date": "2025-01-05"}], "attractions": ["Jaisalmer Fort", "Sam Sand Dunes", "Patwon Ki Haveli"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 20, "condition": "Cool and dry"}, "location": {"lat": 26.9157, "lng": 70.9083}, "entry_fee": 250, "events": [{"name": "Desert Festival", "start_date": "2026-02-01", "end_date": "2026-02-03"}], "avg_cost": 3000},
    {"name": "Jodhpur", "ratings": {"avg": 4.5, "count": 2600}, "reviews": [{"user": "Neha R", "text": "Blue city views from the fort", "rating": 5, "date": "2025-03-01"}], "attractions": ["Mehrangarh Fort", "Jaswant Thada", "Umaid Bhawan Palace"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 23, "condition": "Dry"}, "location": {"lat": 26.2389, "lng": 73.0243}, "entry_fee": 200, "events": [], "avg_cost": 2900},

    {"name": "Manali", "ratings": {"avg": 4.6, "count": 3800}, "reviews": [{"user": "Rohan K", "text": "Snow-capped mountains everywhere", "rating": 5, "date": "2025-05-20"}], "attractions": ["Solang Valley", "Rohtang Pass", "Hadimba Temple"], "season": {"best_months": [3, 4, 5, 6, 9, 10, 12, 1]}, "weather": {"avg_temp": 12, "condition": "Cold"}, "location": {"lat": 32.2432, "lng": 77.1892}, "entry_fee": 0, "events": [], "avg_cost": 2700},
    {"name": "Shimla", "ratings": {"avg": 4.4, "count": 3300}, "reviews": [{"user": "Isha M", "text": "Colonial charm and cool weather", "rating": 4, "date": "2025-06-05"}], "attractions": ["The Ridge", "Mall Road", "Jakhu Temple"], "season": {"best_months": [3, 4, 5, 9, 10, 12]}, "weather": {"avg_temp": 15, "condition": "Cool"}, "location": {"lat": 31.1048, "lng": 77.1734}, "entry_fee": 0, "events": [], "avg_cost": 2500},
    {"name": "Dharamshala", "ratings": {"avg": 4.5, "count": 1900}, "reviews": [{"user": "Tenzin L", "text": "Peaceful monasteries and mountain views", "rating": 5, "date": "2025-04-12"}], "attractions": ["Dalai Lama Temple", "Triund Trek", "Bhagsu Falls"], "season": {"best_months": [3, 4, 5, 9, 10, 11]}, "weather": {"avg_temp": 16, "condition": "Cool"}, "location": {"lat": 32.2190, "lng": 76.3234}, "entry_fee": 0, "events": [], "avg_cost": 2200},

    {"name": "Rishikesh", "ratings": {"avg": 4.6, "count": 4200}, "reviews": [{"user": "Karan V", "text": "Yoga capital with river rafting", "rating": 5, "date": "2025-02-20"}], "attractions": ["Laxman Jhula", "River Rafting", "Beatles Ashram"], "season": {"best_months": [9, 10, 11, 2, 3, 4]}, "weather": {"avg_temp": 22, "condition": "Pleasant"}, "location": {"lat": 30.0869, "lng": 78.2676}, "entry_fee": 0, "events": [{"name": "International Yoga Festival", "start_date": "2026-03-01", "end_date": "2026-03-07"}], "avg_cost": 2000},
    {"name": "Nainital", "ratings": {"avg": 4.4, "count": 2900}, "reviews": [{"user": "Shreya P", "text": "Lake views are gorgeous", "rating": 4, "date": "2025-05-18"}], "attractions": ["Naini Lake", "Snow View Point", "Mall Road Nainital"], "season": {"best_months": [3, 4, 5, 9, 10, 11]}, "weather": {"avg_temp": 18, "condition": "Cool"}, "location": {"lat": 29.3803, "lng": 79.4636}, "entry_fee": 0, "events": [], "avg_cost": 2400},

    {"name": "Agra", "ratings": {"avg": 4.7, "count": 6500}, "reviews": [{"user": "Farhan A", "text": "Taj Mahal is breathtaking at sunrise", "rating": 5, "date": "2025-01-10"}], "attractions": ["Taj Mahal", "Agra Fort", "Fatehpur Sikri"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 22, "condition": "Pleasant"}, "location": {"lat": 27.1767, "lng": 78.0081}, "entry_fee": 1100, "events": [], "avg_cost": 2800},
    {"name": "Varanasi", "ratings": {"avg": 4.5, "count": 5100}, "reviews": [{"user": "Aarav G", "text": "Spiritual atmosphere on the ghats", "rating": 5, "date": "2025-03-08"}], "attractions": ["Ganga Aarti", "Kashi Vishwanath Temple", "Assi Ghat"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 20, "condition": "Cool"}, "location": {"lat": 25.3176, "lng": 82.9739}, "entry_fee": 0, "events": [{"name": "Dev Deepawali", "start_date": "2025-11-15", "end_date": "2025-11-15"}], "avg_cost": 2100},

    {"name": "Darjeeling", "ratings": {"avg": 4.5, "count": 2400}, "reviews": [{"user": "Sonam T", "text": "Toy train and tea gardens", "rating": 5, "date": "2025-04-25"}], "attractions": ["Tiger Hill", "Darjeeling Toy Train", "Batasia Loop"], "season": {"best_months": [3, 4, 5, 10, 11]}, "weather": {"avg_temp": 14, "condition": "Cool"}, "location": {"lat": 27.0410, "lng": 88.2663}, "entry_fee": 0, "events": [], "avg_cost": 2600},

    {"name": "Goa", "ratings": {"avg": 4.5, "count": 8900}, "reviews": [{"user": "Leo D", "text": "Beaches and nightlife are amazing", "rating": 5, "date": "2025-01-25"}], "attractions": ["Baga Beach", "Fort Aguada", "Dudhsagar Falls"], "season": {"best_months": [11, 12, 1, 2, 3]}, "weather": {"avg_temp": 28, "condition": "Warm"}, "location": {"lat": 15.2993, "lng": 74.1240}, "entry_fee": 0, "events": [{"name": "Sunburn Festival", "start_date": "2025-12-27", "end_date": "2025-12-30"}], "avg_cost": 3500},

    {"name": "Alleppey", "ratings": {"avg": 4.6, "count": 3100}, "reviews": [{"user": "Devika S", "text": "Houseboat stay was unforgettable", "rating": 5, "date": "2025-02-18"}], "attractions": ["Backwater Houseboats", "Alleppey Beach", "Kumarakom Bird Sanctuary"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 27, "condition": "Warm"}, "location": {"lat": 9.4981, "lng": 76.3388}, "entry_fee": 0, "events": [], "avg_cost": 3300},
    {"name": "Kochi", "ratings": {"avg": 4.4, "count": 3600}, "reviews": [{"user": "Manoj T", "text": "Great mix of history and culture", "rating": 4, "date": "2025-03-15"}], "attractions": ["Fort Kochi", "Chinese Fishing Nets", "Mattancherry Palace"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 28, "condition": "Warm and humid"}, "location": {"lat": 9.9312, "lng": 76.2673}, "entry_fee": 0, "events": [], "avg_cost": 2400},

    {"name": "Kodaikanal", "ratings": {"avg": 4.4, "count": 2200}, "reviews": [{"user": "Swathi N", "text": "Misty hills and lake views", "rating": 4, "date": "2025-05-02"}], "attractions": ["Kodaikanal Lake", "Coaker's Walk", "Pillar Rocks"], "season": {"best_months": [3, 4, 5, 9, 10]}, "weather": {"avg_temp": 16, "condition": "Cool"}, "location": {"lat": 10.2381, "lng": 77.4892}, "entry_fee": 0, "events": [], "avg_cost": 2300},
    {"name": "Madurai", "ratings": {"avg": 4.5, "count": 2900}, "reviews": [{"user": "Ganesh R", "text": "Meenakshi Temple architecture is stunning", "rating": 5, "date": "2025-02-05"}], "attractions": ["Meenakshi Temple", "Thirumalai Nayakkar Palace", "Gandhi Museum"], "season": {"best_months": [10, 11, 12, 1, 2]}, "weather": {"avg_temp": 27, "condition": "Warm"}, "location": {"lat": 9.9252, "lng": 78.1198}, "entry_fee": 0, "events": [], "avg_cost": 1900},

    {"name": "Andaman Islands", "ratings": {"avg": 4.7, "count": 2100}, "reviews": [{"user": "Reema J", "text": "Crystal clear waters, scuba diving", "rating": 5, "date": "2025-01-30"}], "attractions": ["Radhanagar Beach", "Cellular Jail", "Havelock Island"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 29, "condition": "Tropical"}, "location": {"lat": 11.7401, "lng": 92.6586}, "entry_fee": 0, "events": [], "avg_cost": 5500},

    {"name": "Leh Ladakh", "ratings": {"avg": 4.8, "count": 3400}, "reviews": [{"user": "Tashi D", "text": "Pangong Lake is otherworldly", "rating": 5, "date": "2025-06-10"}], "attractions": ["Pangong Lake", "Nubra Valley", "Leh Palace"], "season": {"best_months": [5, 6, 7, 8, 9]}, "weather": {"avg_temp": 15, "condition": "Cold and dry"}, "location": {"lat": 34.1526, "lng": 77.5771}, "entry_fee": 0, "events": [{"name": "Hemis Festival", "start_date": "2026-06-25", "end_date": "2026-06-26"}], "avg_cost": 4500},

    {"name": "Ranthambore", "ratings": {"avg": 4.5, "count": 1800}, "reviews": [{"user": "Vivek S", "text": "Spotted a tiger on safari", "rating": 5, "date": "2025-03-20"}], "attractions": ["Ranthambore National Park", "Ranthambore Fort", "Safari Zones"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 24, "condition": "Dry"}, "location": {"lat": 26.0173, "lng": 76.5026}, "entry_fee": 500, "events": [], "avg_cost": 3800},

    {"name": "Mumbai", "ratings": {"avg": 4.3, "count": 7200}, "reviews": [{"user": "Rohit M", "text": "City that never sleeps", "rating": 4, "date": "2025-04-01"}], "attractions": ["Gateway of India", "Marine Drive", "Elephanta Caves"], "season": {"best_months": [11, 12, 1, 2]}, "weather": {"avg_temp": 30, "condition": "Humid"}, "location": {"lat": 19.0760, "lng": 72.8777}, "entry_fee": 0, "events": [], "avg_cost": 3600},

    {"name": "Amritsar", "ratings": {"avg": 4.7, "count": 3900}, "reviews": [{"user": "Gurpreet S", "text": "Golden Temple is deeply moving", "rating": 5, "date": "2025-02-14"}], "attractions": ["Golden Temple", "Wagah Border", "Jallianwala Bagh"], "season": {"best_months": [10, 11, 12, 1, 2, 3]}, "weather": {"avg_temp": 21, "condition": "Pleasant"}, "location": {"lat": 31.6340, "lng": 74.8723}, "entry_fee": 0, "events": [], "avg_cost": 2000},

    {"name": "Shillong", "ratings": {"avg": 4.5, "count": 1600}, "reviews": [{"user": "Ibarisha K", "text": "Scotland of the East, living root bridges", "rating": 5, "date": "2025-05-25"}], "attractions": ["Living Root Bridges", "Elephant Falls", "Umiam Lake"], "season": {"best_months": [3, 4, 5, 10, 11]}, "weather": {"avg_temp": 19, "condition": "Cool"}, "location": {"lat": 25.5788, "lng": 91.8933}, "entry_fee": 0, "events": [], "avg_cost": 2900}
]

result = db.destinations.insert_many(destinations)
print(f"Inserted {len(result.inserted_ids)} destinations")
